//  [
//     {
//         "description": "Radiate Elegance on Your Wedding Day with Our Sky Blue Art Deco Earrings: Gold Fan and Baroque Flat Round Freshwater Pearls! Step into timeless beauty with our exquisite sky blue wedding earrings. Featuring art deco-inspired gold fan accents and baroque flat round freshwater pearls, each pair captures the essence of vintage charm and modern sophistication.",
//         "discount": "0.00",
//         "discounted_price": "30.88",
//         "gemstone": "Pearl",
//         "id": 1,
//         "image_paths": [
//             "Baroque Pearl Bridal Earrings: Sky Blue Art Deco Gold Fan.png",
//             "Baroque Pearl Bridal Earrings: Sky Blue Art Deco Gold Fan2.png",
//             "Baroque Pearl Bridal Earrings: Sky Blue Art Deco Gold Fan3.png",
//             "Baroque Pearl Bridal Earrings: Sky Blue Art Deco Gold Fan4.png",
//             "Baroque Pearl Bridal Earrings: Sky Blue Art Deco Gold Fan5.png"
//         ],
//         "materials": "Yellow gold",
//         "original_price": "30.88",
//         "product_name": "Baroque Pearl Bridal Earrings:Sky Blue Art Deco Gold Fan",
//         "quantity_in_stock": 8,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": null,
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Featuring exceptional luster and nacre, this piece showcases the unique beauty of baroque pearls. The irregular shape of the gold design perfectly complements the distinct form of the baroque pearl, while the gold setting enhances its natural luster. With its simple yet sophisticated design, this jewelry piece is truly timeless.",
//         "discount": "15.00",
//         "discounted_price": "24.55",
//         "gemstone": "",
//         "id": 2,
//         "image_paths": [
//             "Big Keshi Pearl Earrings: Baroque Dangle.png",
//             "Big Keshi Pearl Earrings: Baroque Dangle2.png",
//             "Big Keshi Pearl Earrings: Baroque Dangle3.png",
//             "Big Keshi Pearl Earrings: Baroque Dangle4.png",
//             "Big Keshi Pearl Earrings: Baroque Dangle5.png"
//         ],
//         "materials": "Yellow gold",
//         "original_price": "28.88",
//         "product_name": "Big Keshi Pearl Earrings: Baroque Dangle",
//         "quantity_in_stock": 3,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "9-10mm / 12-13mm (Pearl)",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "This stunning piece features rich and vibrant abalone shells, beautifully accented with gold edges, and paired with delicate white freshwater petal pearls. The combination of colorful abalone and elegant pearls creates a unique and eye-catching design, perfect for adding a touch of sophistication and luxury to any outfit.",
//         "discount": "20.00",
//         "discounted_price": "24.70",
//         "gemstone": null,
//         "id": 3,
//         "image_paths": [
//             "Abalone &Baroque Pearl Dangle Earrings: S925 Sterling Silver.png",
//             "Abalone &Baroque Pearl Dangle Earrings: S925 Sterling Silver2.png",
//             "Abalone &Baroque Pearl Dangle Earrings: S925 Sterling Silver3.png",
//             "Abalone &Baroque Pearl Dangle Earrings: S925 Sterling Silver4.png",
//             "Abalone &Baroque Pearl Dangle Earrings: S925 Sterling Silver5.png"
//         ],
//         "materials": "Brass, Shell, Silver, Yellow gold",
//         "original_price": "30.88",
//         "product_name": "Abalone & Baroque Pearl Dangle Earrings: S925 Sterling Silver",
//         "quantity_in_stock": 1,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": " 6-8mm (Pearl)",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "These statement earrings feature a stunning 12-14 mm large white baroque pearl gracefully dangling from a rectangular 925 sterling silver post, plated with 14k gold. A delicate green zircon gemstone is nestled within the rectangle, adding a touch of color and sophistication.",
//         "discount": "20.00",
//         "discounted_price": "64.42",
//         "gemstone": null,
//         "id": 4,
//         "image_paths": [
//             "Baroque Pearl Drop Earrings: Green Zircon, Sterling Silver, 14k Gold.png",
//             "Baroque Pearl Drop Earrings: Green Zircon, Sterling Silver, 14k Gold2.png",
//             "Baroque Pearl Drop Earrings: Green Zircon, Sterling Silver, 14k Gold3.png",
//             "Baroque Pearl Drop Earrings: Green Zircon, Sterling Silver, 14k Gold4.png",
//             "Baroque Pearl Drop Earrings: Green Zircon, Sterling Silver, 14k Gold5.png"
//         ],
//         "materials": "Sterling silver, Yellow gold",
//         "original_price": "80.52",
//         "product_name": "Baroque Pearl Drop Earrings: Green Zircon, Sterling Silver, 14k Gold",
//         "quantity_in_stock": 2,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": " 12-14mm (Pearl)",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Theses earrings are extremely elegant and would look fantastic on whoever has them on. The perfect gift for Mother’s Day, Valentine’s Day, Christmas, Hanukkah, Birthdays, June Birthstone, Engagement, Brides, Bridesmaids or Graduation for any woman, teen, children, adults, daughters, granddaughters, girlfriend, wife, fiancee or that special lady.",
//         "discount": "0.00",
//         "discounted_price": "50.00",
//         "gemstone": " Genuine Tahitian Pearl and Freshwater pearl",
//         "id": 5,
//         "image_paths": [
//             "Tahitian Black Pearl Earrings: 14k Gold Plated, Freshwater Keshi Pearl Dangle.png",
//             "Tahitian Black Pearl Earrings: 14k Gold Plated, Freshwater Keshi Pearl Dangle2.png",
//             "Tahitian Black Pearl Earrings: 14k Gold Plated, Freshwater Keshi Pearl Dangle3.png",
//             "Tahitian Black Pearl Earrings: 14k Gold Plated, Freshwater Keshi Pearl Dangle4.png",
//             "Tahitian Black Pearl Earrings: 14k Gold Plated, Freshwater Keshi Pearl Dangle5.png"
//         ],
//         "materials": "14k heavy gold Plated",
//         "original_price": "50.00",
//         "product_name": "Tahitian Black Pearl Earrings: 14k Gold Plated, Freshwater Keshi Pearl Dangle",
//         "quantity_in_stock": 1,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "about 9-10mm (Tahitian pearl), 5-6 mm (white KESHI freshwater pearl)",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "These Baroque pearl earrings/Freshwater pearl dangle earrings/14k gold biwa pearl drop earrings/Modern pearl jewelry/Rectangle pearl/One of a kind are so pretty and unique.,They are made with freshwater Baroque Biwa pearls and rectangle shaped Baroque pearls. The design used Biwa pearl strung together to the 14k irregular circle shaped posts. The needles are 925 silver.",
//         "discount": "20.00",
//         "discounted_price": "22.40",
//         "gemstone": "Pearl",
//         "id": 6,
//         "image_paths": [
//             "Baroque Pearl Dangle Earrings: 14k Gold Biwa Pearl, Modern Jewelry.png",
//             "Baroque Pearl Dangle Earrings: 14k Gold Biwa Pearl, Modern Jewelry.png2",
//             "Baroque Pearl Dangle Earrings: 14k Gold Biwa Pearl, Modern Jewelry.png3",
//             "Baroque Pearl Dangle Earrings: 14k Gold Biwa Pearl, Modern Jewelry.png4",
//             "Baroque Pearl Dangle Earrings: 14k Gold Biwa Pearl, Modern Jewelry.png5"
//         ],
//         "materials": "Brass, Silver, Yellow gold",
//         "original_price": "28.00",
//         "product_name": "Baroque Pearl Dangle Earrings: 14k Gold Biwa Pearl, Modern Jewelry",
//         "quantity_in_stock": 2,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": null,
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "This simple and stylish cross pearl necklace can be worn alone or layered with other chains or pearl strands. The cross is a nucleated pearl, giving it a baroque shape, but each pearl is hand-selected for symmetry and high quality.This delicate and minimalist necklace is ideal for everyday wear. The cross-shaped pearl adds a unique touch, making it a perfect gift for Easter, Thanksgiving, and church.",
//         "discount": "0.00",
//         "discounted_price": "28.99",
//         "gemstone": "Pearl",
//         "id": 7,
//         "image_paths": [
//             "Baroque Freshwater Pearl Cross Necklace - Titanium Steel Chain.png",
//             "Baroque Freshwater Pearl Cross Necklace - Titanium Steel Chain2.png",
//             "Baroque Freshwater Pearl Cross Necklace - Titanium Steel Chain3.png",
//             "Baroque Freshwater Pearl Cross Necklace - Titanium Steel Chain4.png",
//             "Baroque Freshwater Pearl Cross Necklace - Titanium Steel Chain5.png"
//         ],
//         "materials": "Silver, Stainless steel, Titanium, Yellow gold",
//         "original_price": "28.99",
//         "product_name": "Baroque Freshwater Pearl Cross Necklace - Titanium Steel Chain",
//         "quantity_in_stock": 20,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": null,
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Introducing our exquisite Tahitian Pearl jewelry, featuring vibrant, richly colored Tahitian pearls paired with intricately carved black mother-of-pearl shell pieces.Each piece is meticulously crafted from high-quality 14k gold-filled material, ensuring durability and a luxurious finish. The captivating colors of the Tahitian pearls, ranging from deep greens to striking blues, beautifully complement the elegant designs of the carved mother-of-pearl, making this collection a perfect statement for any occasion.",
//         "discount": "0.00",
//         "discounted_price": "68.00",
//         "gemstone": "Pearl",
//         "id": 8,
//         "image_paths": [
//             "14k Gold Filled Tahitian Black Pearl Earrings: Genuine AA Grade.png",
//             "14k Gold Filled Tahitian Black Pearl Earrings: Genuine AA Grade2.png",
//             "14k Gold Filled Tahitian Black Pearl Earrings: Genuine AA Grade3.png",
//             "14k Gold Filled Tahitian Black Pearl Earrings: Genuine AA Grade4.png",
//             "14k Gold Filled Tahitian Black Pearl Earrings: Genuine AA Grade5.png"
//         ],
//         "materials": "Yellow gold",
//         "original_price": "68.00",
//         "product_name": "14k Gold Filled Tahitian Black Pearl Earrings: Genuine AA Grade",
//         "quantity_in_stock": 1,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": null,
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "This beautiful bracelet features a striking combination of half baroque cross pearls and half twist knot gold chain. The genuine freshwater cultured pearls showcase irregular shapes and a stunning luster,",
//         "discount": "20.00",
//         "discounted_price": "27.90",
//         "gemstone": "Pearl",
//         "id": 9,
//         "image_paths": [
//             "Baroque Cross Pearl Bracelet: Gold Chain Toggle Bracelet.png",
//             "Baroque Cross Pearl Bracelet: Gold Chain Toggle Bracelet2.png",
//             "Baroque Cross Pearl Bracelet: Gold Chain Toggle Bracelet3.png",
//             "Baroque Cross Pearl Bracelet: Gold Chain Toggle Bracelet4.png",
//             "Baroque Cross Pearl Bracelet: Gold Chain Toggle Bracelet5.png"
//         ],
//         "materials": "Brass, Yellow gold",
//         "original_price": "34.88",
//         "product_name": "Baroque Cross Pearl Bracelet: Gold Chain Toggle Bracelet",
//         "quantity_in_stock": 8,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "20-22cm (8\"-8.5\")",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "This exquisite piece features delicate gold accents paired with white cross pearls, each adorned with green zirconia. The combination of refined gold enhances the elegance of the white pearls, creating a sophisticated and eye-catching accessory.",
//         "discount": "20.00",
//         "discounted_price": "26.39",
//         "gemstone": "Freshwater baroque pearls in cross-shaped",
//         "id": 10,
//         "image_paths": [
//             "Freshwater Pearl Cross Dangle Earrings: Gold Bridal Statement.png",
//             "Freshwater Pearl Cross Dangle Earrings: Gold Bridal Statement2.png",
//             "Freshwater Pearl Cross Dangle Earrings: Gold Bridal Statement3.png",
//             "Freshwater Pearl Cross Dangle Earrings: Gold Bridal Statement4.png",
//             "Freshwater Pearl Cross Dangle Earrings: Gold Bridal Statement5.png"
//         ],
//         "materials": "18k gold finish with S925 sliver post (perfect for sensitive skin)",
//         "original_price": "32.99",
//         "product_name": "Freshwater Pearl Cross Dangle Earrings: Gold Bridal Statement",
//         "quantity_in_stock": 8,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": null,
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Dainty Handpicked White Freshwater Stars Baroque Pearl Gold Necklace. This elegant necklace features three handpicked white freshwater star baroque pearls, offering a touch of sophistication and charm. Designed for versatility, it can be worn in three different styles by easily adjusting the small gold ball clasp. Whether you prefer a delicate choker, a classic mid-length, or a stylish long necklace, this piece adapts effortlessly to your look.",
//         "discount": "0.00",
//         "discounted_price": "34.88",
//         "gemstone": null,
//         "id": 11,
//         "image_paths": [
//             "18k Gold Lariat Necklace: Freshwater Star Pearl Y Necklace.png",
//             "18k Gold Lariat Necklace: Freshwater Star Pearl Y Necklace2.png",
//             "18k Gold Lariat Necklace: Freshwater Star Pearl Y Necklace3.png",
//             "18k Gold Lariat Necklace: Freshwater Star Pearl Y Necklace4.png",
//             "18k Gold Lariat Necklace: Freshwater Star Pearl Y Necklace5.png"
//         ],
//         "materials": "Yellow Gold plated / 14k Gold Filled",
//         "original_price": "34.88",
//         "product_name": "18k Gold Lariat Necklace: Freshwater Star Pearl Y Necklace",
//         "quantity_in_stock": 3,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "18 Inches, 9-12mm (Pearl)",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "These stunning drop earrings feature three genuine Tahitian pearls, elegantly suspended from a gold-filled satellite chain. The combination of luxurious Tahitian pearls and the gleaming gold-filled chain creates an exquisite and sophisticated accessory.",
//         "discount": "0.00",
//         "discounted_price": "98.00",
//         "gemstone": "Pearl",
//         "id": 12,
//         "image_paths": [
//             "7-10mm| Triple Genuine Tahitian Pearl | Lever Back Earrings.png",
//             "7-10mm| Triple Genuine Tahitian Pearl | Lever Back Earrings2.png",
//             "7-10mm| Triple Genuine Tahitian Pearl | Lever Back Earrings3.png",
//             "7-10mm| Triple Genuine Tahitian Pearl | Lever Back Earrings4.png",
//             "7-10mm| Triple Genuine Tahitian Pearl | Lever Back Earrings5.png"
//         ],
//         "materials": "Yellow gold",
//         "original_price": "98.00",
//         "product_name": "Triple Genuine Tahitian Pearl Earrings",
//         "quantity_in_stock": 1,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "2.5 Inch, 7mm - 9mm (Tahitian pearls)",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Classic and Casual Tahitian Floating Pearl Necklace.This classic and casual Tahitian floating pearl necklace is designed to be a daily favorite. Its timeless elegance ensures it will be a cherished piece, perfect for adding a touch of sophistication to any outfit. Sure to please, this necklace is an ideal choice for everyday wear.",
//         "discount": "0.00",
//         "discounted_price": "135.00",
//         "gemstone": "Pearl",
//         "id": 13,
//         "image_paths": [
//             "10mm Tahitian Pearl Necklace.png",
//             "10mm Tahitian Pearl Necklace2.png",
//             "10mm Tahitian Pearl Necklace3.png",
//             "10mm Tahitian Pearl Necklace4.png",
//             "10mm Tahitian Pearl Necklace5.png"
//         ],
//         "materials": "14k yellow gold filled",
//         "original_price": "135.00",
//         "product_name": "Tahitian Pearl Necklace: 14k Gold-Filled Floating Black Pearl",
//         "quantity_in_stock": 5,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "from 8 to 10mm (Pearl)",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Natural Purple-Gray Freshwater Pearls with Vibrant Tahitian Long Earrings.These exquisite earrings feature natural purple-gray freshwater pearls paired with vibrant, colorful Tahitian pearls. The long design adds a touch of sophistication and elegance, making them a stunning accessory for any occasion.",
//         "discount": "0.00",
//         "discounted_price": "50.00",
//         "gemstone": "Genuine Tahitian Pearl & Freshwater pearl",
//         "id": 14,
//         "image_paths": [
//             "Tahitian Pearl Drop Earrings: 14k Gold Plated, Freshwater Pearls.png",
//             "Tahitian Pearl Drop Earrings: 14k Gold Plated, Freshwater Pearls2.png",
//             "Tahitian Pearl Drop Earrings: 14k Gold Plated, Freshwater Pearls3.png"
//         ],
//         "materials": "Silver",
//         "original_price": "50.00",
//         "product_name": "Tahitian Pearl Drop Earrings: 14k Gold Plated, Freshwater Pearls",
//         "quantity_in_stock": 5,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "about 9-10mm (Tahitian pearl) 5-6 mm ( freshwater pearl)",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "7mm Japanese seawater sliver Akoya pearl dropping earrings with Moon and sparkling celestial stars in small cubic zirconia.",
//         "discount": "0.00",
//         "discounted_price": "65.00",
//         "gemstone": "Cultured Gray Akoya pearls",
//         "id": 15,
//         "image_paths": [
//             "Gray Akoya Pearl Dangle Earrings: Sterling Silver Moon & Stars.png",
//             "Gray Akoya Pearl Dangle Earrings: Sterling Silver Moon & Stars2.png",
//             "Gray Akoya Pearl Dangle Earrings: Sterling Silver Moon & Stars3.png",
//             "Gray Akoya Pearl Dangle Earrings: Sterling Silver Moon & Stars4.png",
//             "Gray Akoya Pearl Dangle Earrings: Sterling Silver Moon & Stars5.png"
//         ],
//         "materials": null,
//         "original_price": "65.00",
//         "product_name": "Gray Akoya Pearl Dangle Earrings: Sterling Silver Moon & Stars",
//         "quantity_in_stock": 2,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "7mm (Japanese seawater sliver Akoya pearl)",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Snowflake Brooch with Blue-Grey Akoya Pearl.This stunning snowflake brooch is adorned with zirconia stones, creating a dazzling winter-inspired design. At its center, a blue-grey Akoya pearl adds a touch of elegance and sophistication. Perfect for enhancing the wintry white ambiance of the season, this brooch brings a refined and festive touch to any outfit.",
//         "discount": "20.00",
//         "discounted_price": "27.90",
//         "gemstone": "Genuine Akoya Pearl, saltwater pearl",
//         "id": 16,
//         "image_paths": [
//             "Japanese Akoya Sliver Brooch.png",
//             "Japanese Akoya Sliver Brooch2.png",
//             "Japanese Akoya Sliver Brooch3.png",
//             "Japanese Akoya Sliver Brooch4.png",
//             "Japanese Akoya Sliver Brooch5.png"
//         ],
//         "materials": null,
//         "original_price": "34.88",
//         "product_name": "Japanese Akoya Sliver Brooch\n",
//         "quantity_in_stock": 8,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "7-7.5mm diameter",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Gold Stainless Steel Two-Layer Sideways Cross Necklace. Elevate your everyday style with our Gold Stainless Steel Two-Layer Sideways Cross Necklace—a perfect accessory that seamlessly blends fashion with faith. Crafted with precision, this necklace is a tasteful addition to your wardrobe and a meaningful symbol of devotion.",
//         "discount": "20.00",
//         "discounted_price": "26.30",
//         "gemstone": "Pearl",
//         "id": 17,
//         "image_paths": [
//             "Gold Stainless Steel Pearl Cross Necklace: Two-Layer Religious Jewelry.png",
//             "Gold Stainless Steel Pearl Cross Necklace: Two-Layer Religious Jewelry2.png",
//             "Gold Stainless Steel Pearl Cross Necklace: Two-Layer Religious Jewelry3.png",
//             "Gold Stainless Steel Pearl Cross Necklace: Two-Layer Religious Jewelry4.png",
//             "Gold Stainless Steel Pearl Cross Necklace: Two-Layer Religious Jewelry5.png"
//         ],
//         "materials": "Stainless steel, Steel, Titanium, Yellow gold",
//         "original_price": "32.88",
//         "product_name": "Gold Stainless Steel Pearl Cross Necklace: Two-Layer Religious Jewelry",
//         "quantity_in_stock": 1,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "18 Inches",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "This exquisite pair of earrings features two genuine freshwater Keshi pearls and rare cross-shaped pearls with a striking metallic luster. The unique cross shape is particularly rare in the market, making these earrings a standout choice for anyone seeking a distinctive and elegant accessory.",
//         "discount": "20.00",
//         "discounted_price": "27.10",
//         "gemstone": null,
//         "id": 18,
//         "image_paths": [
//             "Baroque Cross Pearl Hoop Earrings: Freshwater Pearl Dangle.png",
//             "Baroque Cross Pearl Hoop Earrings: Freshwater Pearl Dangle2.png",
//             "Baroque Cross Pearl Hoop Earrings: Freshwater Pearl Dangle3.png",
//             "Baroque Cross Pearl Hoop Earrings: Freshwater Pearl Dangle4.png",
//             "Baroque Cross Pearl Hoop Earrings: Freshwater Pearl Dangle5.png"
//         ],
//         "materials": "Yellow gold",
//         "original_price": "33.88",
//         "product_name": "Baroque Cross Pearl Hoop Earrings: Freshwater Pearl Dangle",
//         "quantity_in_stock": 1,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "17-18mm (Hoop Size),About 68mm (Totally length)",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "These Freshwater baroque pearl earrings/Baroque pearl earrings/petal pearl earrings/Pearl drop earrings are so modern and chic. They are made with freshwater Baroque pearls and petal Keshi pearls with the highest quality 14k GP settings. As you can see from the pictures, all pearls have stunning lusters. The earring backs are 14k gold with 925 silver needles.",
//         "discount": "20.00",
//         "discounted_price": "25.60",
//         "gemstone": "Pearl",
//         "id": 19,
//         "image_paths": [
//             "Freshwater baroque pearl hoop earrings.png",
//             "Freshwater baroque pearl hoop earrings2.png",
//             "Freshwater baroque pearl hoop earrings3.png",
//             "Freshwater baroque pearl hoop earrings4.png",
//             "Freshwater baroque pearl hoop earrings5.png"
//         ],
//         "materials": "Brass, Silver, Yellow gold",
//         "original_price": "32.00",
//         "product_name": "Freshwater baroque pearl hoop earrings",
//         "quantity_in_stock": 1,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": null,
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "AAA quality, real freshwater baroque pearl earrings. It’s dainty jewelry and can be worn every day.A special piece you’ll treasure and Safe for sensitive skin.Great gift choice for your girlfriend, mom, wife, or your best friend.",
//         "discount": "20.00",
//         "discounted_price": "38.40",
//         "gemstone": "Genuine Large Baroque Pearls",
//         "id": 20,
//         "image_paths": [
//             "Baroque Pearl Swan Brooch Pendant: Freshwater Pearl, CZ Rhinestone.png",
//             "Baroque Pearl Swan Brooch Pendant: Freshwater Pearl, CZ Rhinestone2.png",
//             "Baroque Pearl Swan Brooch Pendant: Freshwater Pearl, CZ Rhinestone3.png",
//             "Baroque Pearl Swan Brooch Pendant: Freshwater Pearl, CZ Rhinestone4.png",
//             "Baroque Pearl Swan Brooch Pendant: Freshwater Pearl, CZ Rhinestone5.png"
//         ],
//         "materials": "sterling silver, 18k gold",
//         "original_price": "48.00",
//         "product_name": "Baroque Pearl Swan Brooch Pendant: Freshwater Pearl, CZ Rhinestone",
//         "quantity_in_stock": 1,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "around 15-20mm in width",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Delicate Gold Accents with Green Zirconia-Embedded White Cross Pearls.This exquisite piece features delicate gold accents paired with white cross pearls, each adorned with green zirconia. The combination of refined gold and vibrant green stones enhances the elegance of the white pearls, creating a sophisticated and eye-catching accessory.",
//         "discount": "20.00",
//         "discounted_price": "27.90",
//         "gemstone": "Pearl",
//         "id": 21,
//         "image_paths": [
//             "Freshwater Pearl Cross Earrings: Gold & Green Zirconia Dangle Earrings.png",
//             "Freshwater Pearl Cross Earrings: Gold & Green Zirconia Dangle Earrings2.png",
//             "Freshwater Pearl Cross Earrings: Gold & Green Zirconia Dangle Earrings3.png",
//             "Freshwater Pearl Cross Earrings: Gold & Green Zirconia Dangle Earrings4.png",
//             "Freshwater Pearl Cross Earrings: Gold & Green Zirconia Dangle Earrings5.png"
//         ],
//         "materials": "Yellow gold",
//         "original_price": "34.88",
//         "product_name": "Freshwater Pearl Cross Earrings: Gold & Green Zirconia Dangle Earrings",
//         "quantity_in_stock": 2,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": null,
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Pearls are timeless, and this bar of 4 gorgeous Japanese Slivery Blue Akoya pearls.It's a dainty little everyday necklace",
//         "discount": "0.00",
//         "discounted_price": "83.00",
//         "gemstone": "Pearl",
//         "id": 22,
//         "image_paths": [
//             "Akoya Pearl Necklace: S925 Silver, Blue-Grey Pearl & CZ Pendant.png",
//             "Akoya Pearl Necklace: S925 Silver, Blue-Grey Pearl & CZ Pendant2.png",
//             "Akoya Pearl Necklace: S925 Silver, Blue-Grey Pearl & CZ Pendant3.png",
//             "Akoya Pearl Necklace: S925 Silver, Blue-Grey Pearl & CZ Pendant4.png",
//             "Akoya Pearl Necklace: S925 Silver, Blue-Grey Pearl & CZ Pendant5.png"
//         ],
//         "materials": "Yellow gold",
//         "original_price": "83.00",
//         "product_name": "Akoya Pearl Necklace: S925 Silver, Blue-Grey Pearl & CZ Pendant",
//         "quantity_in_stock": 1,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "6.5-7mm",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Frame work is 18kt white gold plated over copper alloy with rhinestone details,Security pin in back. The pictures were taken in natural daylight and reflect the true colors of the item. Each monitor displays color differently, so they may appear slightly lighter or darker in true life.",
//         "discount": "0.00",
//         "discounted_price": "88.00",
//         "gemstone": "Genuine Tahitian pearl, saltwater pearl",
//         "id": 23,
//         "image_paths": [
//             "Tahitian Pearl Lotus Brooch: White Gold Plated Flower Pin.png",
//             "Tahitian Pearl Lotus Brooch: White Gold Plated Flower Pin2.png",
//             "Tahitian Pearl Lotus Brooch: White Gold Plated Flower Pin3.png",
//             "Tahitian Pearl Lotus Brooch: White Gold Plated Flower Pin4.png",
//             "Tahitian Pearl Lotus Brooch: White Gold Plated Flower Pin5.png"
//         ],
//         "materials": null,
//         "original_price": "88.00",
//         "product_name": "Tahitian Pearl Lotus Brooch: White Gold Plated Flower Pin",
//         "quantity_in_stock": 2,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "about 11mm diameter",
//         "total_revenue": "0.00"
//     },
//     {
//         "description": "Featuring high-quality blue-grey Akoya pearls and a classic single zirconia design, this piece captures the brilliance of a blue starry night. Its simple yet elegant design exudes sophistication and charm, making it a timeless accessory for any occasion.",
//         "discount": "0.00",
//         "discounted_price": "55.00",
//         "gemstone": "High-Quality Blue-Grey Akoya Pearl",
//         "id": 24,
//         "image_paths": [
//             "Akoya Pearl Pendant: 18k White Gold, CZ Sterling Silver Necklace.png",
//             "Akoya Pearl Pendant: 18k White Gold, CZ Sterling Silver Necklace2.png",
//             "Akoya Pearl Pendant: 18k White Gold, CZ Sterling Silver Necklace3.png",
//             "Akoya Pearl Pendant: 18k White Gold, CZ Sterling Silver Necklace4.png",
//             "Akoya Pearl Pendant: 18k White Gold, CZ Sterling Silver Necklace5.png"
//         ],
//         "materials": "18k white gold plated sterling silver with CZ",
//         "original_price": "55.00",
//         "product_name": "Akoya Pearl Pendant: 18k White Gold, CZ Sterling Silver Chain.png",
//         "quantity_in_stock": 2,
//         "quantity_sold": 0,
//         "revenue": "0.00",
//         "size": "7.5- 8 mm",
//         "total_revenue": "0.00"
//     }
// ] 